name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Manuelles Triggern

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y libreadline-dev

    - name: Build nob
      run: cc -o nob nob.c

    - name: Build mysh
      run: ./nob

    - name: Get Version
      id: get_version
      run: |
        VERSION=$(./build/mysh -v | awk '{print $3}')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Print Version
      run: echo "Detected version: ${{ env.VERSION }}"

    - name: Upload Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ env.VERSION }}" ./build/mysh \
          --title "mysh ${{ env.VERSION }}" \
          --notes "Release for mysh version ${{ env.VERSION }}"