name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install -y libreadline-dev

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install readline

    - name: Set up architecture
      run: |
        if [ "${{ matrix.arch }}" == "arm64" ]; then
          export ARCH_FLAGS="-target aarch64-apple-darwin"
        else
          export ARCH_FLAGS=""
        fi
        echo "ARCH_FLAGS=$ARCH_FLAGS" >> $GITHUB_ENV

    - name: Build nob
      run: cc -o nob nob.c

    - name: Build mysh
      run: ./nob

    - name: Get Version
      id: get_version
      run: |
        VERSION=$(./build/mysh -v | awk '{print $3}')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Rename Binary for Release
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          OS="linux"
        else
          OS="macos"
        fi
        mv build/mysh build/mysh-${OS}-${{ matrix.arch }}

    - name: List build directory
      run: ls -alh build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mysh-${{ matrix.os }}-${{ matrix.arch }}
        path: build/mysh-${{ matrix.os }}-${{ matrix.arch }}
